require:
  - rubocop-gp
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  UseCache: true

inherit_from:
  - './rubocop-gp.yml'
  - './rubocop-lint.yml'
  - './rubocop-layout.yml'
  - './rubocop-metrics.yml'
  - './rubocop-naming.yml'
  - './rubocop-rails.yml'
  - './rubocop-rspec.yml'
  - './rubocop-slim-lint.yml'
  - './rubocop-style.yml'
