Naming/FileName:
  Exclude:
    - Gemfile
    - Gemfile.lock
    - Guardfile

Naming/VariableNumber:
  EnforcedStyle: snake_case
  CheckSymbols: false
  AllowedPatterns: ['_v\d+\z', '(\A|_)h[1-6]\z', 's3']
