Metrics/BlockLength:
  Enabled: true
  CountComments: false
  Max: 75
  AllowedMethods: [describe, context, FactoryBot.define, factory]

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 25

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 25

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
