Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/LinkToBlank:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: true
  ForbiddenMethods:
    - decrement!
    - increment!
    - toggle!
    - update_attribute
    - update_column
    - update_columns

Rails/WhereEquals:
  Enabled: false

Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false
