Lint/UnusedBlockArgument:
  Exclude:
    - app/views/**/*

Style/IdenticalConditionalBranches:
  Exclude:
    - app/views/**/*

Layout/FirstHashElementLineBreak:
  Exclude:
    - app/views/**/*

Gp/ContinuationSlash:
  Exclude:
    - app/views/**/*

Layout/FirstArgumentIndentation:
  Exclude:
    - app/views/**/*
