Rails/HasAndBelongsToMany:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Rails/LinkToBlank:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false
