Lint/UnusedBlockArgument:
  Exclude:
    - !ruby/regexp /\.slim/
    
Style/IdenticalConditionalBranches:
  Exclude:
    - !ruby/regexp /\.slim/
    
Layout/FirstHashElementLineBreak:
  Exclude:
    - !ruby/regexp /\.slim/

Gp/ContinuationSlash:
  Exclude:
    - !ruby/regexp /\.slim/
    
Layout/FirstArgumentIndentation:
  Exclude:
    - !ruby/regexp /\.slim/

Style/RedundantLineContinuation:
  Exclude:
    - !ruby/regexp /\.slim/

Lint/UselessAssignment:
  Exclude:
    - !ruby/regexp /\.slim/
